### ISSUE TITLE
'Nother Command

### ISSUE THREAD

**Issue by Chaotix96** [DDSloan96/ChaosCraft#3]
I rage a lot, so I wanna make a command for the server that will prepare me for my rages..... The command should be /braceyourself. This command will backup the world, so that afterwords, all you (or me) needs do is type /aftermath, which restores the world and restarts the server. Thanks!

**Comment by DDSloan96** [comment]
Will work on, no ETA on completion

**Comment by DDSloan96** [comment]
Too Lazy, Won't Fix
